version: "3.9"
services:
  domyext:
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    image: $CI_REGISTRY_IMAGE:prod-latest
    container_name: domyext
    restart: unless-stopped
    expose:
      - "80"
    networks:
      liliumnet:
        ipv4_address: 192.168.1.8

networks:
  liliumnet:
    external:
      name: liliumnet